In [15]:
import pandas as pd
import pickle
import numpy as np
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

import xgboost as xgb

In [16]:
baseball_data = pd.read_csv('C:/workspace/p-tag/god_father/baseball_2023.csv')

In [17]:
baseball_data

T_ID  VS_T_ID  PA  AB  RUN    OBP    OOO  win
0     0        8  81  78    8  0.284  0.256    0
1     8        0  74  63    8  0.356  0.270    1
2     3        9  94  81   16  0.409  0.333    1
3     9        3  85  78   10  0.365  0.308    0
4     5        6  81  76   14  0.363  0.342    0
5     6        5  83  70   12  0.346  0.257    1
6     4        7  92  78   12  0.344  0.244    0
7     7        4  77  63    9  0.342  0.206    1

In [18]:
baseball_data[['RUN', 'AB', 'PA']] = baseball_data[['RUN', 'AB', 'PA']]/2
baseball_data

T_ID  VS_T_ID    PA    AB  RUN    OBP    OOO  win
0     0        8  40.5  39.0  4.0  0.284  0.256    0
1     8        0  37.0  31.5  4.0  0.356  0.270    1
2     3        9  47.0  40.5  8.0  0.409  0.333    1
3     9        3  42.5  39.0  5.0  0.365  0.308    0
4     5        6  40.5  38.0  7.0  0.363  0.342    0
5     6        5  41.5  35.0  6.0  0.346  0.257    1
6     4        7  46.0  39.0  6.0  0.344  0.244    0
7     7        4  38.5  31.5  4.5  0.342  0.206    1

In [19]:
baseball_data.columns

Index(['T_ID', 'VS_T_ID', 'PA', 'AB', 'RUN', 'OBP', 'OOO', 'win'], dtype='object')

In [20]:
train_data = baseball_data[['RUN', 'AB', 'PA', 'OOO', 'T_ID', 'VS_T_ID', 'OBP']]

In [21]:
train_data

RUN    AB    PA    OOO  T_ID  VS_T_ID    OBP
0  4.0  39.0  40.5  0.256     0        8  0.284
1  4.0  31.5  37.0  0.270     8        0  0.356
2  8.0  40.5  47.0  0.333     3        9  0.409
3  5.0  39.0  42.5  0.308     9        3  0.365
4  7.0  38.0  40.5  0.342     5        6  0.363
5  6.0  35.0  41.5  0.257     6        5  0.346
6  6.0  39.0  46.0  0.244     4        7  0.344
7  4.5  31.5  38.5  0.206     7        4  0.342

In [22]:
import pickle
pickled_RandomForest_model = pickle.load(open('C:/workspace/p-tag/model/random_forest.pkl', 'rb'))
pred = pickled_RandomForest_model.predict(train_data)
pred_probs_RandomForest = pickled_RandomForest_model.predict_proba(train_data)
pred_probs_RandomForest


array([[0.76866273, 0.23133727],
       [0.29751666, 0.70248334],
       [0.43647427, 0.56352573],
       [0.5365133 , 0.4634867 ],
       [0.28044922, 0.71955078],
       [0.48622275, 0.51377725],
       [0.53895   , 0.46105   ],
       [0.53357106, 0.46642894]])

In [23]:
pickled_XGBoost_model = pickle.load(open('C:/workspace/p-tag/model/xgboost.pkl', 'rb'))
dtest = xgb.DMatrix(data=train_data)

percent = pickled_XGBoost_model.predict(dtest)
preds = [ 1 if x > 0.5 else 0 for x in percent ]
pred_probs_xgboost = np.array([arr for arr in zip(1-percent,percent)])
pred_probs_xgboost

array([[0.761752  , 0.23824802],
       [0.37841213, 0.6215879 ],
       [0.44093275, 0.55906725],
       [0.6261011 , 0.37389892],
       [0.41117954, 0.58882046],
       [0.48490846, 0.51509154],
       [0.48298782, 0.5170122 ],
       [0.4914462 , 0.5085538 ]], dtype=float32)

In [25]:
pickled_GBM_model = pickle.load(open('C:/workspace/p-tag/model/GBM.pkl', 'rb'))

pred = pickled_GBM_model.predict(train_data)
pred_probs_GBM = pickled_GBM_model.predict_proba(train_data)
pred_probs_GBM


array([[0.84764062, 0.15235938],
       [0.26940196, 0.73059804],
       [0.4192159 , 0.5807841 ],
       [0.58229941, 0.41770059],
       [0.3271821 , 0.6728179 ],
       [0.51517013, 0.48482987],
       [0.5642558 , 0.4357442 ],
       [0.57141653, 0.42858347]])

In [26]:
pred_probs_xgboost = np.array([arr for arr in zip(1-percent,percent)])
pred_probs_xgboost

array([[0.761752  , 0.23824802],
       [0.37841213, 0.6215879 ],
       [0.44093275, 0.55906725],
       [0.6261011 , 0.37389892],
       [0.41117954, 0.58882046],
       [0.48490846, 0.51509154],
       [0.48298782, 0.5170122 ],
       [0.4914462 , 0.5085538 ]], dtype=float32)

In [27]:
pickled_LightGBM_model = pickle.load(open('C:/workspace/p-tag/model/LightGBM.pkl', 'rb'))
pred = pickled_LightGBM_model.predict(train_data)

pred_probs_LightGBM = pickled_LightGBM_model.predict_proba(train_data)
pred_probs_LightGBM

array([[0.80857854, 0.19142146],
       [0.23437902, 0.76562098],
       [0.42432119, 0.57567881],
       [0.66684799, 0.33315201],
       [0.30488244, 0.69511756],
       [0.45787558, 0.54212442],
       [0.44233644, 0.55766356],
       [0.51265582, 0.48734418]])

In [29]:
pickled_DeepLearning_model = pickle.load(open('C:/workspace/p-tag/model/DeepLearning.pkl', 'rb'))

pred_probs_DeepLearning = pickled_DeepLearning_model.predict(train_data)

1/1 [==============================] - 0s 277ms/step


In [30]:
total_pred_probs = (pred_probs_RandomForest + pred_probs_xgboost + pred_probs_GBM + pred_probs_LightGBM + pred_probs_DeepLearning)/5

preds = [1 if total_pred_probs[index][0] < total_pred_probs[index][1] else 0 for index in range(len(total_pred_probs))]
preds

[0, 1, 0, 0, 1, 0, 0, 0]

In [37]:
pred = [1 if pred_probs_DeepLearning[index][0] < pred_probs_DeepLearning[index][1] else 0 for index in range(len(pred_probs_DeepLearning))]
pred

[0, 1, 0, 0, 0, 0, 0, 0]

In [35]:
baseball_data['win']

0    0
1    1
2    1
3    0
4    0
5    1
6    0
7    1
Name: win, dtype: int64

In [31]:
baseball_data

T_ID  VS_T_ID    PA    AB  RUN    OBP    OOO  win
0     0        8  40.5  39.0  4.0  0.284  0.256    0
1     8        0  37.0  31.5  4.0  0.356  0.270    1
2     3        9  47.0  40.5  8.0  0.409  0.333    1
3     9        3  42.5  39.0  5.0  0.365  0.308    0
4     5        6  40.5  38.0  7.0  0.363  0.342    0
5     6        5  41.5  35.0  6.0  0.346  0.257    1
6     4        7  46.0  39.0  6.0  0.344  0.244    0
7     7        4  38.5  31.5  4.5  0.342  0.206    1

In [32]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(baseball_data['win'], preds)))

예측 정확도: 0.5000


In [ ]:
total_pred_probs = (pred_probs_RandomForest + pred_probs_xgboost + pred_probs_GBM + pred_probs_LightGBM + pred_probs_DeepLearning)/5

preds = [1 if total_pred_probs[index][0] < total_pred_probs[index][1] else 0 for index in range(len(total_pred_probs))]